#!/usr/bin/env bash
# advice.sh - Dev advice pools organized by stat affinity
# Sourced by the main fli script. Not executable on its own.
#
# Each array is a pool of advice lines. The pet's stats determine
# which pools are drawn from and how the advice is delivered.
#
# WISDOM    -> insightful, practical, architectural advice
# DEBUGGING -> debugging, testing, error handling tips
# PATIENCE  -> process, craft, long-term thinking advice
# CHAOS     -> creative, unhinged, wildcard takes
# SNARK     -> sarcastic wrappers and delivery modifiers

# --- WISDOM pool (100 lines) ---
ADVICE_WISDOM=(
  "Name things for what they do, not what they are."
  "If you can't explain your architecture to a new hire in 5 minutes, simplify it."
  "The best abstraction is the one you don't notice."
  "Write code that's easy to delete, not easy to extend."
  "Every layer of indirection is a tax on the next developer."
  "If your function needs a comment to explain what it does, rename it."
  "Composition beats inheritance in almost every real-world case."
  "The right data structure eliminates half your code."
  "Don't optimize for a future that may never arrive."
  "A good interface hides complexity. A great interface makes complexity unnecessary."
  "If two things change for different reasons, they belong in different modules."
  "Coupling is the enemy. Every dependency is a promise you'll have to keep."
  "The simplest solution that works is usually the best solution."
  "Code is read 10x more than it's written. Optimize for the reader."
  "If you're copy-pasting, you're missing an abstraction."
  "Small functions with clear names are self-documenting."
  "Don't abstract too early. Wait until you see the pattern three times."
  "A well-named variable eliminates the need for a comment."
  "Separate what changes from what stays the same."
  "The best code is the code you never had to write."
  "Make illegal states unrepresentable in your type system."
  "Prefer explicit over implicit. Future you will thank present you."
  "If your class has more than one reason to change, split it."
  "Design for the common case. Handle the edge case, but don't let it drive the architecture."
  "A leaky abstraction is worse than no abstraction."
  "Keep your dependency tree shallow. Deep trees break in surprising ways."
  "If you need a diagram to explain your code flow, the code flow is too complex."
  "Pure functions are the easiest to test, reason about, and reuse."
  "State is the root of most bugs. Minimize mutable state."
  "The best error message tells you what happened, why, and what to do next."
  "Don't fight the framework. If you're fighting it, you picked the wrong one."
  "Configuration should have good defaults. Override should be the exception."
  "Idempotent operations save you from retry nightmares."
  "If your module needs to know about the internals of another module, your boundaries are wrong."
  "Fail fast, fail loud. Silent failures are the hardest to debug."
  "A good API is obvious. A great API is boring."
  "Encapsulate what varies. Expose what's stable."
  "Prefer immutable data. Mutation is a conversation with the future that you'll lose."
  "The cost of wrong abstraction is higher than the cost of duplication."
  "If you can't test it in isolation, your design has a coupling problem."
  "Every boolean parameter is a code smell. It means your function does two things."
  "Logging is not debugging. Observability is not monitoring. Know the difference."
  "The database schema is the most important design decision you'll make."
  "Normalize until it hurts, denormalize until it works."
  "Eventual consistency is not a bug. It's a design choice you need to be explicit about."
  "If your service needs to call three other services to answer one question, rethink your boundaries."
  "Timeouts are not optional. Every external call needs one."
  "Circuit breakers save systems. Retries without backoff kill them."
  "The CAP theorem is not a menu. You don't get to pick two and ignore the third."
  "Horizontal scaling solves throughput. It doesn't solve latency."
  "Cache invalidation is hard because your mental model of time is wrong."
  "If your microservice can't be deployed independently, it's not a microservice."
  "Shared databases between services are shared mutable state at scale."
  "Event sourcing is powerful but only if you actually need the event history."
  "CQRS adds complexity. Use it when read and write patterns genuinely differ."
  "Queues decouple time. Use them when the producer shouldn't wait for the consumer."
  "Backpressure is a feature, not a bug. Dropping work gracefully beats crashing."
  "Health checks should check actual health, not just return 200."
  "Feature flags are technical debt with an expiration date. Set the date."
  "Semantic versioning only works if you actually follow it."
  "Your CI pipeline is the most important code in your repository."
  "If deploys are scary, you're not deploying often enough."
  "Blue-green deployments are simpler than canary releases. Start there."
  "Rollback plans are not optional. If you can't roll back, you can't ship safely."
  "Infrastructure as code means your infrastructure is reviewable, testable, and reproducible."
  "Secrets don't belong in code, config files, or environment variables baked into images."
  "Least privilege is not paranoia. It's engineering."
  "Defense in depth means assuming every layer will fail."
  "Input validation at the boundary. Trust nothing from outside your system."
  "SQL injection is a solved problem. If you have it, you're not using parameterized queries."
  "CORS is not security. It's a browser policy. Your API still needs auth."
  "Authentication tells you who. Authorization tells you what. Don't confuse them."
  "JWTs are not session tokens. They can't be revoked without extra infrastructure."
  "Rate limiting protects you from your users. Circuit breakers protect you from your dependencies."
  "Encryption at rest and in transit is table stakes, not a feature."
  "Audit logs are not optional for anything touching money or personal data."
  "The principle of least astonishment applies to APIs, UIs, and CLIs equally."
  "Good defaults reduce configuration. Great defaults eliminate it."
  "Backwards compatibility is a feature. Breaking changes are a cost."
  "Deprecation warnings are promises. Honor them with a migration path."
  "Documentation is a product. Treat it like one."
  "README-driven development forces you to think about the user before the implementation."
  "If your error says 'something went wrong', you've failed the user."
  "Metrics without alerts are just numbers. Alerts without runbooks are just noise."
  "SLOs are contracts with your users. SLIs are how you measure them. SLAs are the consequences."
  "The 99th percentile matters more than the average."
  "Distributed tracing is not optional in a microservice architecture."
  "Structured logging beats grep. Always."
  "If you can't reproduce it locally, add more observability."
  "Dashboards should answer questions, not raise them."
  "On-call rotations without runbooks are just suffering."
  "Post-mortems without action items are just storytelling."
  "Blameless culture doesn't mean accountability-free culture."
  "The fastest code is the code that doesn't run."
  "Measure before you optimize. Intuition about performance is usually wrong."
  "Premature optimization is the root of all evil, but mature optimization is the root of all speed."
  "Big-O notation tells you the shape, not the speed. Constants matter."
  "Memory allocation is the hidden cost in most hot paths."
  "Connection pools exist for a reason. Don't open a new connection per request."
  "Batch operations beat N+1 queries every single time."
)

# --- DEBUGGING pool (100 lines) ---
ADVICE_DEBUGGING=(
  "Read the error message. No, actually read it. The whole thing."
  "The bug is never where you think it is. Start from what you know is true."
  "Add a log line before and after the suspicious code. The gap tells the story."
  "If it works on your machine but not in prod, the difference IS the bug."
  "Binary search your codebase. Comment out half, see if it still breaks."
  "The most recent change is the most likely cause. Check git log first."
  "Rubber duck debugging works because explaining forces you to slow down."
  "If you've been stuck for 30 minutes, take a walk. Your subconscious is faster than your debugger."
  "Reproduce it first. If you can't reproduce it, you can't fix it."
  "Write the test that fails before you write the fix."
  "Off-by-one errors account for 50% of all bugs. Or maybe 51%."
  "Null pointer exceptions mean you assumed something existed that doesn't."
  "Race conditions only appear when you're not looking. Add sleep(1) to prove they exist."
  "If the bug is intermittent, it's a timing issue, a resource issue, or both."
  "Stack traces read bottom to top. Your code is at the top. The cause is in the middle."
  "When debugging, change one thing at a time. Otherwise you're just guessing."
  "The debugger is not cheating. Use it."
  "Printf debugging is valid. Don't let anyone tell you otherwise."
  "If the fix is a try-catch that swallows the exception, you haven't fixed anything."
  "Correlation is not causation, especially in distributed systems."
  "Check the logs. Then check the other logs. Then check the logs you didn't know existed."
  "If it works in debug mode but not release mode, it's an optimization or timing issue."
  "Memory leaks are just objects that overstayed their welcome."
  "If your test passes when run alone but fails in the suite, you have shared state."
  "Flaky tests are not flaky. They're telling you about a real problem you don't understand yet."
  "The bug you can't find is in the code you trust the most."
  "Assertions in dev, monitoring in prod. Both catch bugs. Different bugs."
  "If you're debugging for more than an hour, explain the problem to someone. Anyone."
  "Check your assumptions. Then check them again. One of them is wrong."
  "The simplest explanation is usually correct. Occam's razor applies to bugs too."
  "If the data looks wrong, trace it back to where it entered the system."
  "Encoding issues are always UTF-8 vs something else. Always."
  "Timezone bugs only appear at midnight, on DST boundaries, or in demos."
  "If your regex doesn't work, your regex is wrong. Regexes are never wrong about what they match."
  "Deadlocks happen when two things wait for each other. Draw the dependency graph."
  "If the API returns 200 but the data is wrong, the bug is in the contract, not the status code."
  "Caching bugs are the hardest to find because the system lies to you."
  "If it worked yesterday and doesn't work today, something changed. Find what changed."
  "DNS is always the problem. Even when it isn't, check DNS first."
  "If your container works locally but not in k8s, check env vars, mounts, and network policies."
  "Segfaults mean you're reading or writing memory you don't own. Check your pointers and indices."
  "If the test is hard to write, the code is hard to use. That's feedback."
  "Integration tests catch the bugs unit tests miss. Unit tests catch the bugs integration tests are too slow to find."
  "If you're mocking everything, you're testing your mocks, not your code."
  "The best debugging tool is a good night's sleep."
  "If the error message is unhelpful, improve it. That's a valid fix."
  "Logs should tell a story. Timestamp, context, what happened, why it matters."
  "If you can't explain why the fix works, you haven't found the root cause."
  "Bisect your git history. The bug was introduced in a specific commit. Find it."
  "If the system is slow, profile it. Don't guess where the bottleneck is."
  "Network issues look like application bugs. Application bugs look like network issues."
  "If the database query is slow, check the execution plan before adding an index."
  "Connection timeouts and read timeouts are different problems with different fixes."
  "If your async code deadlocks, you're probably awaiting on the wrong thread."
  "Thread safety bugs only manifest under load. Test under load."
  "If the file exists but the code says it doesn't, check permissions and paths."
  "Environment variable typos are invisible bugs. Print them at startup."
  "If the response is empty, check if the request actually reached the server."
  "CORS errors are browser errors. Your API doesn't know about CORS. Check the server config."
  "If the websocket disconnects randomly, check your load balancer's idle timeout."
  "SSL certificate errors mean the cert is expired, self-signed, or for the wrong domain."
  "If the build fails only in CI, check the CI environment's versions and dependencies."
  "Docker layer caching can serve stale dependencies. Bust the cache when in doubt."
  "If the migration fails, check if it's already been partially applied."
  "Circular dependencies cause import errors that look like the module doesn't exist."
  "If the JSON parse fails, the JSON is malformed. Pretty-print it and look for the syntax error."
  "Whitespace bugs are real. Trailing spaces, BOM markers, CRLF vs LF."
  "If the cookie isn't being sent, check the domain, path, secure flag, and SameSite attribute."
  "Session bugs are state bugs. Stateless is easier to debug."
  "If the redirect loop won't stop, your auth middleware is redirecting to a page that requires auth."
  "If the email isn't arriving, check spam, SPF, DKIM, and DMARC before blaming the code."
  "If the cron job didn't run, check the timezone of the cron daemon."
  "If the webhook isn't firing, check if the endpoint is publicly accessible."
  "If the queue is growing but consumers are running, check if messages are being nacked and requeued."
  "If the metric looks wrong, check if the metric is measuring what you think it's measuring."
  "If the dashboard shows a spike, check if the spike is real or if the collection interval changed."
  "If the alert fired but nothing is wrong, fix the alert, not the system."
  "If the rollback didn't fix it, the problem isn't in the code you rolled back."
  "If the hotfix introduced a new bug, your hotfix process needs a test step."
  "If the same bug keeps coming back, you're fixing symptoms, not causes."
  "If the code works but you don't know why, you don't understand the code."
  "If the test is green but the feature is broken, the test is testing the wrong thing."
  "If the linter is wrong, configure it. Don't disable it."
  "If the type system says it's wrong, the type system is probably right."
  "If the compiler warning seems harmless, fix it anyway. Warnings accumulate."
  "If the dependency update broke something, read the changelog before downgrading."
  "If the error only happens on Tuesdays, check for scheduled jobs that run on Tuesdays."
  "If the error only happens for one user, check their data, not your code."
  "If the error only happens at scale, your code has an O(n^2) hiding somewhere."
  "If the error only happens once, add monitoring and wait. It'll happen again."
  "If the error happens every time, congratulations. That's the easiest kind to fix."
  "If you fixed the bug but don't know how to test for it, write the test anyway."
  "If the production database is different from dev, that's your bug."
  "If the API changed and nobody told you, that's a process bug. Fix the process."
  "If the documentation is wrong, the documentation is the bug."
  "If the stack overflow answer is from 2012, verify it still applies."
  "If the error message says 'unexpected token', you have a syntax error. Check the line before the reported line."
  "If the promise is rejected but nothing catches it, you have a silent failure."
  "If the event listener fires twice, you registered it twice."
  "If the animation stutters, you're doing layout work in the render loop."
)

# --- PATIENCE pool (100 lines) ---
ADVICE_PATIENCE=(
  "Have you tried waiting? Like, just waiting?"
  "Rome wasn't built in a day. Your CRUD app won't be either."
  "Take a deep breath. The code isn't going anywhere."
  "Step away from the keyboard. Touch grass. Come back."
  "The compile is still running. Relax."
  "You don't have to refactor everything today."
  "Sleep on it. Seriously. Sleep is a debugging tool."
  "The best commit is the one you didn't rush."
  "If you're angry at the code, the code has already won."
  "Patience is just debugging yourself."
  "Your future self is begging you to slow down right now."
  "The code will still be broken tomorrow. Rest."
  "Rushing a fix at 2am creates two bugs by 9am."
  "Every senior dev was once deleting node_modules in frustration."
  "It's okay to not understand the whole codebase on day one."
  "The PR can wait until morning. Your brain can't."
  "Rewriting from scratch feels good but rarely is good."
  "If you've restarted the server 15 times, the problem isn't the server."
  "Learning a new framework takes weeks, not a weekend."
  "You're not slow. The problem is genuinely hard."
  "Progress is invisible until it isn't. Keep going."
  "The best developers aren't fast. They're consistent."
  "Mastery is just patience that forgot to quit."
  "Don't compare your chapter 1 to someone else's chapter 20."
  "Every expert was once a beginner who didn't give up."
  "The codebase didn't get messy overnight. It won't get clean overnight either."
  "Refactoring is a marathon, not a sprint."
  "Small improvements compound. Ship the tiny fix."
  "You don't need to understand monads today. Or ever, honestly."
  "The best time to refactor was last month. The second best time is next sprint."
  "Legacy code is just code that survived long enough to matter."
  "Technical debt is a mortgage, not a crime. Manage it."
  "Not every TODO needs to be done today."
  "The perfect is the enemy of the shipped."
  "Version 1 doesn't need to be perfect. It needs to exist."
  "Ship it, learn from it, improve it. In that order."
  "You'll rewrite this in 6 months anyway. Ship what works now."
  "Incremental progress beats heroic effort every time."
  "A 1% improvement every day is a 37x improvement in a year."
  "Don't optimize what you haven't measured."
  "The right time to add that feature is when users ask for it."
  "YAGNI is not laziness. It's discipline."
  "Build the simplest thing that could possibly work. Then iterate."
  "Prototypes are meant to be thrown away. Let them go."
  "The first draft of anything is garbage. That's normal."
  "Code review takes time because it should take time."
  "Reading code is harder than writing it. Budget accordingly."
  "Understanding the problem takes longer than writing the solution."
  "The best architecture emerges from iteration, not upfront design."
  "Plans are useless. Planning is essential."
  "Estimates are guesses. Treat them that way."
  "If the estimate is always wrong, the process is wrong, not the developer."
  "Deadlines are negotiable. Quality is not."
  "Crunch doesn't produce better software. It produces burned-out developers."
  "Sustainable pace beats heroic sprints over any meaningful timeline."
  "The team that ships every week beats the team that ships every quarter."
  "Continuous delivery is a patience practice disguised as an engineering practice."
  "Migrations take three times longer than you think. Plan for that."
  "Database migrations are the most patient work in software. Respect them."
  "Backwards compatibility is patience made manifest in code."
  "Deprecation is a promise that requires patience to fulfill."
  "Supporting old APIs is tedious but it's what trust looks like."
  "The boring technology choice is usually the patient one."
  "New frameworks are exciting. Maintained frameworks are valuable."
  "Chasing every new tool is a form of procrastination."
  "Depth beats breadth. Master one thing before collecting five."
  "The developer who reads the docs outperforms the one who guesses."
  "Reading source code is slow but it's the only way to truly understand."
  "Pair programming feels slow but produces fewer bugs and better designs."
  "Code reviews feel slow but catch bugs that testing misses."
  "Writing tests feels slow but debugging without them is slower."
  "Documentation feels slow but onboarding without it is slower."
  "Meetings feel slow but misalignment is slower."
  "Planning feels slow but rework is slower."
  "Learning feels slow but ignorance is slower."
  "Mentoring feels slow but growing the team is the highest leverage activity."
  "Teaching forces you to understand. That's why it's worth the time."
  "The best teams invest in making each other better, not just shipping faster."
  "Process exists to reduce friction, not to create it. If it creates friction, fix the process."
  "Automation is patience encoded. Build it once, benefit forever."
  "CI pipelines are slow because they're thorough. Be grateful."
  "Flaky tests are a patience tax. Pay it down by fixing them."
  "Monitoring is patience infrastructure. You're investing in future calm."
  "On-call is easier when you invested patience in reliability."
  "Incident response rewards the team that practiced patience in preparation."
  "Post-mortems are patience rituals. They prevent future suffering."
  "Blameless culture requires patience with human error."
  "Growing as a developer is a years-long project. Enjoy the process."
  "The skills that matter most - communication, empathy, judgment - take the longest to develop."
  "Senior developers aren't faster. They waste less time on the wrong thing."
  "Knowing when not to code is the most patient skill of all."
  "The hardest problems in software are people problems. Those take the most patience."
  "Trust is built slowly and destroyed quickly. Be patient with your team."
  "Good culture is a long game. Every interaction compounds."
  "The best engineering organizations optimize for sustainability, not speed."
  "Patience with yourself is the foundation of patience with your code."
  "You're doing better than you think. Keep going."
  "The fact that you care enough to improve means you're already ahead."
  "Mastery isn't a destination. It's a direction."
  "Every line you write teaches you something. Even the bad ones."
)

# --- CHAOS pool (100 lines) ---
ADVICE_CHAOS=(
  "Delete the database. See what happens."
  "Ship it on Friday at 5pm. Live dangerously."
  "Who needs types? Just cast everything to any."
  "Comments are for the weak. Real code explains itself through vibes."
  "Tabs AND spaces. In the same file. Assert dominance."
  "Name your variables after your enemies."
  "The best error handling is no error handling."
  "Just wrap it in a try-catch and move on with your life."
  "Regex solves everything. If it didn't work, you need more regex."
  "Have you tried deleting node_modules and reinstalling? Works 60% of the time, every time."
  "The real test suite is production."
  "Staging is just production with fewer users."
  "Who needs a load balancer? Just buy a bigger server."
  "Microservices? Make it nano-services. One function per container."
  "Put the password in the README. Nobody reads READMEs anyway."
  "Version control is optional if you believe in yourself."
  "Just copy the whole function and change one line. Abstraction is overrated."
  "The best documentation is a Slack message from 2019 that nobody can find."
  "Deploy manually via SSH. Automation is for people who don't trust themselves."
  "Write the entire application in a single file. Monolith means one file, right?"
  "Use a blockchain. For everything. Even the todo list."
  "AI will fix it. Just ship the broken version."
  "The compiler is just a suggestion engine."
  "Lint rules are more like lint guidelines."
  "Who needs a design doc? Just start coding and see where it goes."
  "The best meeting is the one you skip to write code instead."
  "Rewrite it in Rust. That fixes everything."
  "Just add another dependency. What's one more?"
  "Your package.json has 200 dependencies? Those are rookie numbers."
  "Monorepo everything. One repo to rule them all."
  "Polyrepo everything. Freedom for every microservice."
  "The real architecture is the friends we made along the way."
  "Just use eval. It's basically a feature."
  "Globals are just dependency injection for brave people."
  "Singletons are fine. Fight me."
  "Inheritance 7 levels deep builds character."
  "The best API is no API. Just share the database."
  "REST is dead. GraphQL is dead. Just use websockets for everything."
  "Cache everything forever. Invalidation is a myth."
  "Just restart the service. If it works after restart, it's not a bug."
  "The cloud is just someone else's computer that you pay too much for."
  "Kubernetes is simple. You just need 47 YAML files."
  "Docker solves the 'works on my machine' problem by making it not work on anyone's machine equally."
  "Serverless means you don't have to think about servers. Until you do."
  "NoSQL means you don't need a schema. Until you do."
  "Agile means no planning. That's what it means, right?"
  "Scrum is just meetings with extra steps."
  "Story points are astrology for project managers."
  "The sprint is a social construct."
  "Just mark all tickets as done. Velocity goes up."
  "The standup could have been a Slack message."
  "The Slack message could have been silence."
  "Code review is just reading someone else's code and feeling superior."
  "The best pull request is the one with 5000 lines and no description."
  "Squash all commits into one. History is written by the victors."
  "Force push to main. Establish dominance."
  "The git history is a novel. Nobody reads novels anymore."
  "Merge conflicts build character."
  "Rebasing is just lying about history. Embrace the chaos of merge commits."
  "The real bug was the assumptions we made along the way."
  "If the tests pass, ship it. If they don't pass, delete the tests and ship it."
  "100% code coverage means 0% of your tests are meaningful."
  "Mocking everything means you're testing nothing. But the coverage number looks great."
  "End-to-end tests are just prayers with assertions."
  "The best test is a user clicking around in production."
  "Chaos engineering is just breaking things on purpose and calling it science."
  "Canary deployments are just letting some users suffer first."
  "Feature flags are just if-statements with a management console."
  "A/B testing is just not being able to make decisions."
  "The best monitoring is a user tweeting that your site is down."
  "Alerting at 3am builds resilience. In your resignation letter."
  "The incident retrospective is just group therapy with a Jira ticket."
  "SLAs are just promises you'll break eventually."
  "The 99.99% uptime guarantee doesn't include planned maintenance windows."
  "Horizontal scaling is just throwing money at the problem. And it works."
  "Premature optimization is the root of all evil. So never optimize. Ever."
  "The O(n^2) algorithm is fine. Your dataset will never grow. Trust me."
  "Memory leaks are just your program getting more ambitious over time."
  "The garbage collector will handle it. That's literally its job."
  "Stack overflow? Just increase the stack size. Problem solved."
  "Recursion is just a loop that believes in itself."
  "The best data structure is a JSON blob in a text column."
  "Normalize your database? In this economy?"
  "The migration will be fine. Just run it in production without testing."
  "Backups are for pessimists."
  "The disaster recovery plan is 'hope it doesn't happen'."
  "Security through obscurity works if you're obscure enough."
  "The password policy is 'password1' with increasing numbers."
  "HTTPS is optional if you believe in the goodness of humanity."
  "SQL injection is just user-generated queries. It's a feature."
  "The firewall rule is 'allow all'. Simplicity is elegance."
  "Chaos is just order that hasn't been documented yet."
  "Every production outage is a learning opportunity you didn't ask for."
  "The most creative solutions come from constraints you didn't choose."
  "Break the rules, but know which rules you're breaking and why."
  "The best innovations look irresponsible until they work."
  "Controlled chaos is how you find the edges of your system."
  "If you never break anything, you're not pushing hard enough."
  "The sweet spot is right between 'this is fine' and 'everything is on fire'."
  "Embrace the entropy. Software is a living system. It wants to be messy."
)

# --- SNARK pool (100 lines) ---
ADVICE_SNARK=(
  "Oh, you're using var in 2026? Bold."
  "Sure, commit directly to main. What could go wrong?"
  "Ah yes, the classic 'it works on my machine' defense."
  "Your code doesn't need comments because nobody will ever read it anyway."
  "Congratulations on your spaghetti code. Very al dente."
  "That's a lot of nested if-statements. Are you building a maze?"
  "Your function is 500 lines long. That's not a function, that's a novel."
  "Oh, you hardcoded the API key? Brave choice."
  "I see you've chosen violence today. Deploying on Friday, are we?"
  "Your variable names are so descriptive. 'x', 'temp', 'data2'. Poetry."
  "Ah, the old 'copy-paste from Stack Overflow without reading it' technique."
  "Your git commit message says 'fix'. Fix what? Fix how? Fix why?"
  "That TODO comment has been there since 2019. It's not a TODO, it's a WONTDO."
  "You wrote a 2000-line CSS file. That's not styling, that's a cry for help."
  "Your package.json has more dependencies than your app has features."
  "Oh, you're catching Exception and doing nothing with it? Living dangerously."
  "That regex looks like your cat walked across the keyboard."
  "Your database has no indexes. I too like to live life in the slow lane."
  "Ah yes, storing passwords in plain text. A classic vintage approach."
  "Your API returns 200 for everything. Even errors. Especially errors."
  "That's a creative use of global variables. By creative I mean terrifying."
  "Your test suite has one test and it's marked @Ignore. Impressive coverage."
  "Oh, you wrote your own auth system? I'm sure it's very secure."
  "Your microservice has 47 dependencies and does one thing. Efficiently."
  "That's not technical debt. That's technical bankruptcy."
  "Your code review comment says 'LGTM' on a 3000-line PR. Thorough."
  "Ah, the classic 'rewrite everything from scratch' proposal. Third time this quarter."
  "Your standup update was 'same as yesterday'. For the fifth day in a row."
  "Oh, you deployed without testing? I admire your confidence."
  "Your error handling strategy is 'log and pray'. A spiritual approach."
  "That's not a code smell. That's a code stench."
  "Your architecture diagram needs an architecture diagram."
  "Oh, you're using a NoSQL database for relational data? Adventurous."
  "Your CI pipeline takes 45 minutes. That's not continuous, that's occasional."
  "Ah yes, the 'just restart it' school of incident response."
  "Your config file has more lines than your application code."
  "Oh, you wrote the documentation? In a Google Doc? That nobody can find?"
  "Your sprint velocity is measured in excuses per standup."
  "That's not a monolith. That's a monument to ambition."
  "Your logging strategy is console.log('here'). Very informative."
  "Oh, you named the variable 'final_final_v2_REAL'. Very reassuring."
  "Your retry logic retries forever. That's not resilience, that's stubbornness."
  "Ah, the old 'works in Postman' defense. The API equivalent of 'works on my machine'."
  "Your database migration is irreversible. I too like to burn bridges."
  "Oh, you put business logic in the controller? MVC stands for Massive View Controller now?"
  "Your code has more commented-out blocks than actual code. A graveyard of ideas."
  "That's not a race condition. That's a race certainty."
  "Your error messages are in three different languages. Internationalization?"
  "Oh, you're using setTimeout to fix a race condition? That's not a fix, that's a prayer."
  "Your dependency tree has circular references. It's dependencies all the way down."
  "Ah yes, checking in the node_modules folder. Bold strategy."
  "Your API has no rate limiting. I'm sure nobody will abuse that."
  "Oh, you wrote a custom ORM? Because the existing 47 weren't enough?"
  "Your function returns sometimes a string, sometimes a number, sometimes null. Surprise typing."
  "That's not polymorphism. That's just confusion."
  "Your code works by accident. The tests prove it works. Nothing proves why."
  "Oh, you used a map where you needed a flatMap? Classic."
  "Your singleton has a public constructor. That's not a singleton, that's an optimist."
  "Ah, the classic 'it's not a bug, it's a feature' reframe."
  "Your cron job runs every second. That's not a cron job, that's a while loop."
  "Oh, you put the entire app state in a single Redux store? That's not state management, that's hoarding."
  "Your CSS has 47 !important declarations. When everything is important, nothing is."
  "That's not a memory leak. Your app is just very attached to its objects."
  "Your API versioning strategy is 'hope nobody notices the breaking changes'."
  "Oh, you wrote the same utility function in three different services? DRY is just a suggestion."
  "Your docker image is 4GB. That's not a container, that's a cargo ship."
  "Ah yes, running as root in the container. Security is for other people."
  "Your environment has 200 env vars. That's not configuration, that's a novel."
  "Oh, you used reflection to access private fields? Laws are just suggestions."
  "Your build script is 800 lines of bash. That's not a script, that's a lifestyle."
  "That's not a code review. That's a code roast."
  "Your PR description says 'please review'. That's not a description, that's a plea."
  "Oh, you force-pushed to the shared branch? Rewriting history, are we?"
  "Your git history is a straight line of 'wip' commits. A masterclass in communication."
  "Ah, the classic 'works on my machine' Dockerfile. FROM my-machine:latest."
  "Your monitoring dashboard has 200 panels. That's not observability, that's a screensaver."
  "Oh, you alert on every 500 error? Enjoy your 3am wake-up calls."
  "Your runbook says 'ask Dave'. Dave left the company two years ago."
  "That's not an SLA. That's an aspiration."
  "Your incident postmortem action item is 'be more careful'. Groundbreaking."
  "Oh, you estimated that at 2 story points? It's been three sprints."
  "Your backlog has 847 tickets. That's not a backlog, that's a graveyard."
  "Ah yes, the 'quick fix' that took three weeks. Classic."
  "Your technical design doc is a Slack message that says 'let's just do it'."
  "Oh, you skipped the code review because it was urgent? Every bug was urgent once."
  "Your definition of done is 'it compiles'. Ambitious."
  "That's not a hack. That's a permanent temporary solution."
  "Your feature flag has been on for two years. That's not a flag, that's a load-bearing boolean."
  "Oh, you named the branch 'test123'? Very descriptive."
  "Your README says 'TODO: write README'. Self-referential documentation."
  "Ah, the classic 'I'll add tests later'. Later never comes."
  "Your code is so DRY it's dehydrated. Sometimes a little repetition is clarity."
  "Oh, you abstracted everything into 12 layers? Congratulations, nobody can find the logic."
  "Your clever one-liner saves one line and costs ten minutes of reading. Great trade."
  "That premature optimization saved 2 milliseconds and cost 2 weeks of debugging."
  "Your over-engineered solution is a monument to a problem that doesn't exist yet."
  "Oh, you designed for 10 million users? You have 12. And two are bots."
  "Your code is technically correct. The best kind of correct. And the worst kind of readable."
  "Ah yes, sarcasm in code reviews. The hallmark of a healthy team culture."
  "Behind every sarcastic developer is someone who cares too much about code quality."
)
